### PR TITLE
Basic Jekyll setup - added project page

### PR DESCRIPTION
**Pull request by frankleonrose**

### CODE REVIEW

**Comment by mimiflynn** [comment]
Sorry, just saw this. Will this build to a `/docs`?

**Comment by frankleonrose** [comment]
NP. No need to put it in the `/docs` directory. If we keep the name `things-nyc.github.io` it just generates to that domain name. If we restore the name to `thethings.nyc` then the site will generate to `things-nyc.github.io/thethings.nyc` which can't be pointed to using DNS only.

**Comment by mimiflynn** [comment]
My experience differs: I have several sites running off of GitHub pages using dns and a cname file where the repo name is the fqdn. I have no sites using the GitHub io domain. They all use /docs for the build directory. Please refer to my personal GitHub: mimiflynn.com, iwaspromisedcookies.com, etc.

The issue I’m running into with the fqdn thethings.nyc is that I do not have access to the registrar, only our hosting account. Seems the registrar is different than our hosting company.

Sent via hand computer

**Comment by frankleonrose** [comment]
Aha. Thanks for the pushback. Now I get it. I had thought it was just simple rules ([GH Pages](https://help.github.com/articles/user-organization-and-project-pages/)) + DNS: if the repo name doesn't conform to `username.github.io`, then it gets published to `username.github.io/reponame`. But there's no way for DNS to help redirect to a path. What I didn't understand was that if the repo has a CNAME file then the publishing system does whatever is necessary to serve those correctly (Perhaps building a global URL rewrite list to map `mydomain.com` -> `username.github.io/mydomain-site-repo`).

To your original question, which I assume was actually "does it build *from* /docs", the answer is still no, no need. Since the whole repo is the site, why put the content in /docs? That feature is for repos of projects that want a companion site where the site can be contained within the /docs folder.

**Comment by mimiflynn** [comment]
I see what you mean. I will have to look at this static site generator more closely. I assumed the project would need to output files to serve statically in a directory separately from the code that generated it.

I specifically asked about /docs because the repo settings page has three options to choose from: master root directory, master /docs directory, and gh-pages root directory.

Let me know your thoughts, any of these ways is fine with me.

Sent via hand computer

**Comment by frankleonrose** [comment]
GH Pages runs Jekyll and who knows where the generated files go? That's their problem, on their server.

Yeah, the `master/docs` and `gh-pages/` options are for separating the doc site from your project. Since this repo represents the site itself, makes sense for it to be sourced from `master/`.

**Comment by frankleonrose** [comment]
I do wish there were support for specifying a branch from which to generate a preview site. I'd like to send around a link for people to look at a proposed update prior to publishing. Now they'd have to pull and serve locally or I'd have to manually push it somewhere.

**Pull request merged**
